### ISSUE TITLE
max_overflow parameter is not working

### ISSUE THREAD

**Issue by pushkarnarayan** [altairbow/django-db-connection-pool#1]
I have set the pool_size to 5 and max_overflow to 5 and have done the load testing. So as i am increasing the load , new connections are being created crossing 10 (pool_size + max_overflow). 
Also after the app use total number of ideal connections in Mysql is 10 instead of 5 as the pool_size is 5.

**Comment by altairbow** [comment]
Can you show your pool configuration?
PS. the pool config key 'POOL' has been changed to 'POOL_OPTIONS', if you still use 'POOL', you will get 
```bash
pool_default_params = {
    'pool_size': 10,
    'max_overflow': 10
}
```
see dj_db_conn_pool.backends.pool_default_params

**Comment by pushkarnarayan** [comment]
I guess pool_size and max_overflow are in capital letters too. Also i need pool_recycle option. Is there any way to do this?

**Comment by altairbow** [comment]
POOL_OPTIONS only accept  two parameters: 'pool_size', 'max_overflow', and they must be in lowercase letters,

```
'POOL_OPTIONS '{
    'pool_size': 5,
    'max_overflow': 5
}
```
should meet your requirements

**Comment by altairbow** [comment]
yes, POOL_OPTIONS only accept two parameters: 'pool_size', 'max_overflow' now, and they must be in capital letters

Here's explanation of `recycle`
```
        :param recycle: If set to a value other than -1, number of
          seconds between connection recycling, which means upon
          checkout, if this timeout is surpassed the connection will be
          closed and replaced with a newly opened connection. Defaults to -1.
```
why do you really need this parameter?
