### ISSUE TITLE
Django run error

### ISSUE THREAD

**Issue by BanjiYao** [altairbow/django-db-connection-pool#17]
django.core.exceptions.ImproperlyConfigured: 'dj_db_conn_pool.backends.oracle' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
Error was: No module named 'dj_db_conn_pool'

**Comment by altairbow** [comment]
Have you installed django-db-connection-pool yet? try to import dj_db_conn_pool manually in Django shell.
