### ISSUE TITLE
Is still alive the project?

### ISSUE THREAD

**Issue by Allan-Nava** [altairbow/django-db-connection-pool#20]

**Comment by altairbow** [comment]
Need help？
or any PR？

**Comment by Allan-Nava** [comment]
I'm trying to handle multiple pool connections but is not keeping live

**Comment by Allan-Nava** [comment]
> Need help？
> or any PR？

But with the pool connections it is possible to let connected the connections ??

**Comment by altairbow** [comment]
Any detail about your needs? I can't get it.

**Comment by altairbow** [comment]
django-db-connection-pool can hold connections to mutil-databases in mutilthreading and mutilprocessing based django environment, it's the basic function of django-db-connection-pool

**Comment by Allan-Nava** [comment]
it doesn't work properly

**Comment by altairbow** [comment]
Would you mind to provide any detail about "it doesn't work properly"? 
Post a stack traceback at least...

**Comment by Allan-Nava** [comment]
Need to have the pool connection always alive
