### ISSUE TITLE
OperationalError SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by mishrsoumitra** [altairbow/django-db-connection-pool#43]
**Describe the bug**
We are seeing a lot of the below errors after switching to django-db-connection-pool, before we never saw this issue.
OperationalError
SSL SYSCALL error: EOF detected

**Environment**
- Python Version: 3.9.16
- Django Version: 3.2.14

**Traceback**
django/db/backends/utils.py in _execute at line 84

        with self.db.wrap_database_errors:
            if params is None:
                # params default might be backend specific.
                return self.cursor.execute(sql)
            else:
                return self.cursor.execute(sql, params) <-- line number 84

**Comment by altairbow** [comment]
Can you provide more details？

**Comment by mishrsoumitra** [comment]
Hello,
Thanks for replying. What more details are required?

**Comment by altairbow** [comment]
In the case of using `django.db.backends.postgresql`, does the problem reproduce?
