### ISSUE TITLE
The _ConnectionFairy.connection attribute is deprecated

### ISSUE THREAD

**Issue by mdantonio** [altairbow/django-db-connection-pool#44]
**Describe the bug**
With sqlalchemy 2.0+ a deprecation warning is raised.
`driver_connection` has been [introduced with sqlalchemy 1.4.24](https://docs.sqlalchemy.org/en/20/changelog/changelog_14.html#change-627d533e5d20e3e0af8b3e1ec2777036) and `connection` has been deprecated in favor of this with sqlachemy 2.
Since 1.4.24 is exactly the [minimum version required by `django-db-connection-pool`](https://github.com/altairbow/django-db-connection-pool/blob/147a582034b4f1aac7d06eeab5105b088b057303/setup.py#L38) I hope that the fix can be easily introduced.

**Environment**
- Python Version: 3.10.8
- Django Version: 4.1.7
- SQLAlchemy Version: 2.0.4

**Traceback**
```
  /usr/local/lib/python3.10/site-packages/dj_db_conn_pool/core/mixins.py:104: 
      SADeprecationWarning: The _ConnectionFairy.connection attribute is deprecated;
            please use 'driver_connection' (deprecated since: 2.0)
    self.alias, conn.connection)
```

**Comment by pencil** [comment]
@altairbow Thanks for fixing this! Could you please push a new version with this fix to PyPi?

**Comment by altairbow** [comment]
> @altairbow Thanks for fixing this! Could you please push a new version with this fix to PyPi?

Sure,  [1.2.5](https://pypi.org/project/django-db-connection-pool/1.2.5/) has been released
