### ISSUE TITLE
Save not committing when using pool

### ISSUE THREAD

**Issue by boscharun** [altairbow/django-db-connection-pool#5]
Tried out connetion pool and it worked great for read queries. However, when saving, the queries doesn't seem to commit and hence not able to write anything to db.
Not 100% sure its the commit not working, assuming so because there were no errors in the output.

Config -

> 'default': {
>         'ENGINE': 'dj_db_conn_pool.backends.oracle',
>         'NAME': 'xxx',
>         'USER': 'xxxx',
>         'PASSWORD': 'xxx',
>         'CONN_MAX_AGE': 250,  # For ATP, the timeout period at db end seen to be 5 mins.
>         'POOL_OPTIONS': {
>             'POOL_SIZE': 5,
>             'MAX_OVERFLOW': 5,
>             'autocommit': True,
>         },
>     }

**Comment by altairbow** [comment]
在获取数据库连接时，django会调用django.db.utils.ConnectionHandler(settings.DATABASES).ensure_defaults(alias)来确保一些未明确指定的参数 ，其中就有 conn.setdefault('AUTOCOMMIT', True)，在django.db.utils模块的第172行，如果未显性指定AUTOCOMMIT参数，那么dj_db_conn_pool.backends.oracle.base.DatabaseWrapper 实例的autocommit就会被赋值为 True，另外如果需要明确指定 autocommit 参数，请设置与ENGINE同级，而不是在POOL_OPTIONS内，如果你不太明白我的意思，你在django.db.utils模块的第196行设置断点，跑一遍debug就行了

**Comment by boscharun** [comment]
Thanks @altairbow ,

Tried it out the proper syntax bu still the same result. Enabled debugging to print out sql queries and I can see the insert queries running but data is not getting stored. I doubt now if autocommit is the culprit or something else.. My setup-
Python3.6 + django 2.2.1 + Oracle 12C

> 'default': {
>         # 'ENGINE': 'django.db.backends.oracle',
>         'ENGINE': 'dj_db_conn_pool.backends.oracle',
>         'NAME': '***',
>         'USER': '***',
>         'PASSWORD': '***',
>         'AUTOCOMMIT': True,
>         'POOL_OPTIONS': {
>             'POOL_SIZE': 10,
>             'MAX_OVERFLOW': 10
>         }
>     }

**Comment by altairbow** [comment]
很抱歉，眼下我不能重现你的问题，我可以给你提供一个思路：
在 django.db.transaction（django 2.1.5的第177行）模块中找到 Atomic.__exit__ 方法的第一行 connection = get_connection(self.using)，在此处设置断点，debug你的服务，然后做一次事务操作（create、delete、update），看看是否能够执行到（django 2.1.5的第212行）connection.commit()

**Comment by altairbow** [comment]
No feedback, Close.

**Comment by kevin-kessler** [comment]
Dear @boscharun, @altairbow, did you eventually find a solution for this issue? 

I'm facing the same problem with this setup:
Python 3.9, Django 3.2.7, Oracle 19

**Comment by kevin-kessler** [comment]
So it looks like the Oracle connections created with SQLAlchemy (which django-db-connection-pool is based on) have their autocommit flag set to 0 by default. 

A quick test of setting the flag to 1 after the connection has been returned by the pool confirmed the assumption and Django started persisting my changes all of a sudden again.

You can try it yourself by setting the flag in mixins.py of the django-db-connection-pool module.
Line 75 onwards:
`# get one connection from the pool
  conn = db_pool.connect()
  logger.debug(_("got %s's connection from its pool"), self.alias)
  conn.connection.autocommit=1
  return conn`

Careful: the connection object depends on the database backend that you are using and this autocommit attribute might not be available if the connection object is created via a different backend (i.e. different from oracle_cx).
