### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by UttaraRC** [altairbow/django-db-connection-pool#6]
We are trying to execute two tasks concurrently using celery with two different queues of rabbitmq,
one task execute successfully but second task will not succeeded , this will drop mysql connections.
if we try both functions without queuing, it will not give any error.

That means, if concurrent request is passed to mysql that loss  mysql connections. for sequential execution it will works properly.

Please provide solution to overcome this isuue

**Comment by altairbow** [comment]
可能是因为超过了 MySQL wait_timeout 时间限制，尝试设置 POOL_OPTIONS['RECYCLE']试试看

[将pre_ping、echo、timeout更改为可配置参数并添加recycle参数](https://github.com/altairbow/django-db-connection-pool/commit/a5221da295a769ec11c4c51fb1fcd2a5f7952544)

**Comment by altairbow** [comment]
No feedback, Close.
