### ISSUE TITLE
SIGINT not closing connections with celery

### ISSUE THREAD

**Issue by hosler** [altairbow/django-db-connection-pool#8]
When I send a sigint to my celery process using gevent, it appears that the pool connections stay open and the celery process hangs while waiting for all connections to close. How can I close all connections in the pool? I can put that in a worker shutdown hook.

I've tried using pool.dispose on the pools in pool_cotainer, but after reading sqlalchemy docs that appears to leave some connections open.

**Comment by altairbow** [comment]
You should return all connections before calling pool.dispose(), pool.dispose only close connections those has been returned to pool
try this:
1.call .close() on connections you got from pool
3.if pool.checkedout() eq 0, call pool.dispose on the pools in pool_cotainer

**Comment by altairbow** [comment]
No feedback, Close.
